name: 'Auto-update notify'
on:
  pull_request_target:
    types:
      - auto_merge_enabled
jobs:
  notify-about-updates:
    runs-on: self-hosted
    steps:
      - name: Notify the user that I will be watching the PR
        uses: actions/github-script@v6
        with:
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const pr = context.payload.pull_request.number;
            const user = context.payload.pull_request.user.login;
            await github.rest.issues.createComment({
              owner,
              repo,
              pull_number: pr,
              body: `Hey @${user}!\nSince you activated auto-merge I will be watching master-mre for any updates and auto-update your branch.\nKeep in mind I don't check for comments or successful checks. To disable the automatic updates simply disable auto-merge.`
            });
