name: 'Auto-Update To Auto-Merge'
on:
  push:
    branches:
      - 'main'
      - 'master'
      - 'master-mre'
jobs:
  update-pr-branches:
    runs-on: self-hosted
    steps:
      - name: Update all PRs marked to auto-merge
        uses: actions/github-script@v6
        with:
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            // Get all the PRs in the repository
            const pr_list = (await github.rest.pulls.list({
              owner,
              repo
            })).data;
            // Filter only the ones that are on auto-merge
            const auto_merge_prs = pr_list.filter(pr =>
              pr.auto_merge !== null
            );
            // print out some statistics for debug
            console.log('PR count:');
            console.log(pr_list.length);
            console.log('Of which these are on auto-merge:')
            console.log(auto_merge_prs.length);
            // iterate through the interesting PRs
            for (const pr of auto_merge_prs) {
              const user = pr.user.login;
              // debug messages
              console.log(`Updating "${pr.title}", ${user} will be happy!`);
              // update pr branch
              let update_result;
              try {
               update_result = await github.rest.pulls.updateBranch({
                  owner,
                  repo,
                  pull_number: pr.number
                });
              } catch (error) {
                update_result = error.response;
              }
              // outputs a message based on the status...
              switch(update_result.status) {
                case 202:
                  console.log("YES! The PR was updated successfully. The message was...");
                  break;
                case 403: 
                  console.log("Darn! Seems like I don't have permissions? The message was...");
                  break;
                case 422: 
                  console.log("Oops! I think I found an error. The message was...");
                  break;
              }
              console.log(update_result.data.message);
            }


